### ISSUE TITLE
Design Docs Review 

### ISSUE THREAD

**Issue by jliversi** [bcutler94/Robenhood_full_stack#1]
Hey Ben, really great job on your design docs so far. I just have a few recommended changes: 

MVP LIST

Everything looks great, no changes necessary 

SCHEMA 

- [x] On the users table, should portfolio_value have a not null constraint? If not, what is the justification? 
- [x] Based on the actual Robinhood website, the users table should include the user's actual name, as this is what is shown in at the top of the page (as opposed to a username or email, which are both also necessary for the signup) 
- [ ] If we're going to be pinging an API for information regarding stocks to get recent values, do we need to store all of that information in our database as well? Or can we store just the necessary information to know which stock we're asking for in our API and let the rest of it come from the API? For this, you'll need to look at the API itself and see what is and what isn't returned. 
- [x] Will the date on the transactions table ever differ from the created_at or updated_at columns? If not, do we need it? 
- [x] Make sure to go through your schema and add any associations (ex. a user has_many watchlists, etc). 

SAMPLE STATE 

- [x] Your sample state looks really good, but make sure to make any necessary changes to it after making changes to your schema (ex. you'll need to add a key of `name` to the users slice of state so you can render that at the top of the page)

Overall, great work, and I'm looking forward to seeing your fullstack.

**Comment by bcutler94** [comment]
Hi Josh,

Thanks so much for your feedback. I've gone through each of your pointers and made the necessary changes. Below are my comments for each change.

SCHEMA

- I added a not null constraint to the portfolio_value column in the users table. Thanks for catching that.
- I added both a first_name and last_name columns for the user table. Thanks for catching that as well.
- I'd like to touch base with you Monday regarding storing API information in database and just general API details in general.
- The date on a transaction should never differ from the created_at column. Thanks for catching that.
- I've added the belongs_to/has_many associations in the bullet points under each table where necessary. I should note that I have made the user to watchlist association a has_one association and consequently changed the watchlist key in users slice of state from array to integer.

SAMPLE STATE

- Added first_name and last_name keys in users slice of state.

Thanks so much for your feedback. As I mentioned above I'd love to touch base with you to talk about API usage for stock data.
