### ISSUE TITLE
Design Docs Review #2

### ISSUE THREAD

**Issue by jliversi** [bcutler94/Robenhood_full_stack#2]
BACKEND ROUTES 

- [x] No need for a delete company routes 
- [x] Get for watchlist doens't need own Id, just :user_id 
- [x] For watchlist, adding and removing items, try something like: 
        POST /api/watchlists/:watchlist_id/company/:id 
        DELETE /api/watchlists/:watchlist_id/company/:id
- [x] If just adding and removing items, do we need a patch route for watchlists? 

FRONTEND ROUTES 

- [x] Make home page /home for your own convenience sake 
- [x] for /ticker, make it a wildcard (and specify whether this will be an ID or ticker) 
- [x] Go through and add specific componenets. Ex. 
     Stock Show Page
           TopGraphComponent
                 GraphComponent
                 GraphButtons 
           StockIndex
                StockIndexItems
           WatchlistComponent
                    WatchlistItem
        etc....

**Comment by bcutler94** [comment]
Schema
- Deleted columns that stored unnecessary company data
Backend Routes
- Edited backend routes per our conversation
Fronted Routes
- added /home route
- added ticker wildcard
- added components
