### ISSUE TITLE
Complete first MVP (auth)

### ISSUE THREAD

**Issue by bcutler94** [bcutler94/Robenhood_full_stack#3]

**Comment by jliversi** [comment]
- [ ] Have your AuthRoutes redirect to dashboard or something similar as opposed to "/". Currently, if you're logged in, you get stuck at "/" and can't get anywhere else the site. 
- [ ] To address the previous issue, I had to use `dispatch(logout())` in the console to get logged out. These should not be saved on the window in production (only for testing). 
- [ ] Your demo user login returns unauthorized, did you seed on heroku?
- [ ] On your signup page, the link to `Already Started? Log in to complete your application.` should send you to the login page, as opposed to "/home"
- [ ] "/home" should be a protected route, logged in users shouldn't be able to get there. 
- [ ] The feather button in the top right should send you back to "/"
- [ ] Add a footer at the bottom with your github/linkedin/personal site information (kind of like the small footer above the legal info on the real robinhood)

**Comment by jliversi** [comment]
- [ ] The animations that you currently have (on the splash page phones and the sign in button) are cool, but don't appear on the real robinhood. Let's remove those and save those sort of animations for your personal site or another project.
